name = "GeoPUPM"
uuid = "4523a846-9be0-4857-8edc-97dbb97ccbde"
authors = ["Aminofa70 <amin.alibakhshi@upm.es> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
